### ISSUE TITLE
Sierra Leone: Subsite background image

### ISSUE THREAD

**Issue by charlesyoung** [younginnovations/docker-rc-country-subsite#2]
Info from the client. 

Home page background image: See image file attached for the background image - it should look like this below: 

![image](https://cloud.githubusercontent.com/assets/13888372/12957543/ce8f56b8-d035-11e5-82a6-11cc8da49a87.png)

Note: the original image is big (dimensions: 5616 x 3744, size: 1.59 MB). Hope you can compress this to a reasonable size that cannot cause much loading problem on slower connections.

![home_background_image](https://cloud.githubusercontent.com/assets/13888372/12957375/04e9ede6-d035-11e5-8b1e-9e0f5eaf63bd.jpg)

**Comment by sadhakbj** [comment]
We have compressed and updated the background image for SL site.
![home_page](https://cloud.githubusercontent.com/assets/5828622/13046907/a575ea4a-d403-11e5-82d3-395c85f29a0b.png)
