### ISSUE TITLE
Sierra Leone: Home page text

### ISSUE THREAD

**Issue by charlesyoung** [younginnovations/docker-rc-country-subsite#3]
Info from the client. 

The current text is OK. We can keep it and to the footer text which reads:

“This site provides summaries of contracts and their terms to facilitate understanding of important provisions in the documents. These summaries are not interpretations of the documents. Neither the summaries nor the full contracts are complete accounts of all legal obligations related to the projects in question. This site also includes document text that was created automatically; such text may contain errors and differences from the original PDF files. No warranty is made to the accuracy of any content on this website.”

Add 

“For more information please visit the National Minerals Agency website at www.nma.gov.sl or the Ministry of Mines and Mineral Resources website at www.slminerals.org.”

**Comment by sadhakbj** [comment]
We have updated the text. Please check it.

![sl_info](https://cloud.githubusercontent.com/assets/5828622/13046847/4aa89a68-d403-11e5-92b1-62d8cd1e1b64.png)

**Comment by charlesyoung** [comment]
Thanks. Can I ask that the text is displayed in one paragraph i.e. no space between website. and and For.

**Comment by sadhakbj** [comment]
Its fixed now
![sl_3](https://cloud.githubusercontent.com/assets/5828622/13142276/31574ac4-d664-11e5-9781-f22d088b659d.png)
