### ISSUE TITLE
Sierra Leone: Left panel image

### ISSUE THREAD

**Issue by charlesyoung** [younginnovations/docker-rc-country-subsite#4]
Info from the client. 

We have agreed to use the Star of Sierra Leone, a 968.9-carat diamond discovered ‎on 14th of February, 1972 in the Diminco alluvial mines in Koidu. Please change the height of the sidebar from 124px to 240px to display fully like shown here below.

.sidebar-brand {
...
height: 240px !important;
width: 280px;
}

![image](https://cloud.githubusercontent.com/assets/13888372/12957655/7b7abd5e-d036-11e5-985e-a8ddc38ed816.png)

**Comment by sadhakbj** [comment]
We will implement this.

**Comment by sadhakbj** [comment]
Its fixed now.
![sidebar_image](https://cloud.githubusercontent.com/assets/5828622/13142368/9f00d414-d664-11e5-9398-2921156189b8.png)
