### ISSUE TITLE
Sierra Leone: About page

### ISSUE THREAD

**Issue by charlesyoung** [younginnovations/docker-rc-country-subsite#9]
About Transformation in the Minerals Sector:
The Mines and Minerals Act of 2009, which Repeals the Mines and Minerals Act of 1994 was enacted to (i) promote local and foreign investment in the mining sector by introducing new and improved provisions for exploration, mine development and marketing of minerals and mineral secondary processing for the benefit of the people of Sierra Leone; (ii) ensure that management of the mineral sector is transparent and accountable in accordance with international best practice; (iii) promote improved employment practices in the mining sector; (iv) improve the welfare of communities adversely affected by mining; (v) introduce measures to reduce the harmful effects of mining activities on the environment and to provide for other related matters.
With these reforms, the country’s legislators took important steps to improve mining sector governance, enshrining new transparency and accountability practices in the law and enhancing principles of good governance for the extractive sector. 

The reform also saw the establishment of the National Minerals Agency through an act of parliament in 2012, The National Minerals Agency Act (2012). The Agency is responsible for mineral rights management, collection and dissemination of geological information and it also regulates trading of precious minerals in the country. In line with the Government’s Agenda for Prosperity (A4P), the Agency works closely with the Ministry of Mines and Mineral Resources and other key stakeholders to ensure that Sierra Leoneans benefit from the country’s natural resource wealth.

The New Annotated Contracts
When the Government of Sierra Leone grants a mining lease to a company, the company enters into lease agreement with the government which specifies the obligations and rights of both parties, tax and other payment requirements as well as the responsibility of the licence holder to the primary host communities. As a way of promoting transparency in the minerals sector, the Ministry of Mines and Mineral Resources and the National Minerals Agency have both uploaded these mining agreements on their websites.

However, due to the complex nature of legal documents, we are aware of the fact that not everybody can read and easily understand the exact context of these documents. For this reason, we are proud to present to you the Sierra Leone Resource Contract page which provides simplified annotation of the agreements for easy understanding by all concerned.
We thank the Columbia Center on Sustainable Investment, the World Bank Group and UKaid for developing such an innovative application and their support in making Sierra Leone a part of this initiative.

**Comment by sadhakbj** [comment]
We've updated it on SL site. 
Please check it here: http://rc-site-demo.elasticbeanstalk.com/country/public/about
